set(FARSO_SOURCES
src/button.cpp
src/checkbox.cpp
src/colors.cpp
src/container.cpp
src/controller.cpp
src/draw.cpp
src/event.cpp
src/font.cpp
src/label.cpp
src/picture.cpp
src/progressbar.cpp
src/rect.cpp
src/scrollbar.cpp
src/scrolltext.cpp
src/skin.cpp
src/stacktab.cpp
src/surface.cpp
src/textentry.cpp
src/textselector.cpp
src/widget.cpp
src/widgetrenderer.cpp
src/window.cpp
)
set(FARSO_HEADERS
src/button.h
src/checkbox.h
src/colors.h
src/container.h
src/controller.h
src/draw.h
src/event.h
src/font.h
src/label.h
src/picture.h
src/progressbar.h
src/rect.h
src/scrollbar.h
src/scrolltext.h
src/skin.h
src/stacktab.h
src/surface.h
src/textentry.h
src/textselector.h
src/widget.h
src/widgetrenderer.h
src/window.h
)

set(FARSO_OGRE_SOURCES
src/ogre3d/ogredraw.cpp
src/ogre3d/ogrejunction.cpp
src/ogre3d/ogresurface.cpp
src/ogre3d/ogrewidgetrenderer.cpp
)

set(FARSO_OGRE_HEADERS
src/ogre3d/ogredraw.h
src/ogre3d/ogrejunction.h
src/ogre3d/ogresurface.h
src/ogre3d/ogrewidgetrenderer.h
)

